In [1]:
import os
# https://discuss.pytorch.org/t/how-to-change-the-default-device-of-gpu-device-ids-0/1041/24
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   
os.environ["CUDA_VISIBLE_DEVICES"]=f"{1}"

import torch
print(f"current_device:{torch.cuda.current_device()}")
print(f"device_count:{torch.cuda.device_count()}")
device = torch.device("cuda")

current_device:0
device_count:1


In [9]:
import gym
env = gym.make('CartPole-v1')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[ 0.02573004 -0.01465614  0.03378908  0.01222349]
[ 0.02543692  0.17996535  0.03403355 -0.26961   ]
[ 0.02903623  0.37458551  0.02864135 -0.55136726]
[ 0.03652794  0.56929374  0.017614   -0.83489041]
[ 0.04791381  0.37393564  0.0009162  -0.53672047]
[ 0.05539253  0.17880082 -0.00981821 -0.243749  ]
[ 0.05896854 -0.01617953 -0.01469319  0.04582091]
[ 0.05864495  0.17915    -0.01377678 -0.2514614 ]
[ 0.06222795  0.37446594 -0.018806   -0.54845775]
[ 0.06971727  0.17961315 -0.02977516 -0.2617589 ]
[ 0.07330953 -0.01507139 -0.03501034  0.02138588]
[ 0.07300811 -0.20967423 -0.03458262  0.30282032]
[ 0.06881462 -0.40428668 -0.02852621  0.58439919]
[ 0.06072889 -0.59899766 -0.01683823  0.86796126]
[ 4.87489349e-02 -7.93886500e-01  5.20996220e-04  1.15530288e+00]
[ 0.0328712  -0.59877135  0.02362705  0.86278336]
[ 0.02089578 -0.79420688  0.04088272  1.16280055]
[ 0.00501164 -0.98983667  0.06413873  1.46801621]
[-0.01478509 -1.18568231  0.09349906  1.78002449]
[-0.03849874 -0.99172857  0.129099

[ 0.0929259  -0.2307281  -0.05067113  0.24473315]
[ 0.08831134 -0.03492041 -0.04577647 -0.06349235]
[ 0.08761293  0.16082695 -0.04704632 -0.37025939]
[ 0.09082947  0.35658465 -0.0544515  -0.67739755]
[ 0.09796117  0.16225983 -0.06799945 -0.40234316]
[ 0.10120636  0.35827704 -0.07604632 -0.7156659 ]
[ 0.1083719   0.16428547 -0.09035964 -0.44785561]
[ 0.11165761  0.36056167 -0.09931675 -0.7675984 ]
[ 0.11886885  0.55690038 -0.11466872 -1.08980632]
[ 0.13000685  0.36346129 -0.13646484 -0.835192  ]
[ 0.13727608  0.56015719 -0.15316868 -1.16748912]
[ 0.14847922  0.36732326 -0.17651846 -0.92648033]
[ 0.15582569  0.17496755 -0.19504807 -0.69405761]
[ 0.15932504 -0.01699101 -0.20892922 -0.46856077]
Episode finished after 33 timesteps
[0.03715303 0.00133264 0.01379078 0.02388248]
[ 0.03717969 -0.19398434  0.01426843  0.32088446]
[0.0333     0.00093154 0.02068612 0.03273518]
[ 0.03331863  0.19575083  0.02134083 -0.25334995]
[ 0.03723365  0.39056166  0.01627383 -0.53922593]
[ 0.04504488  0.195214

[ 0.04369854  0.21367817 -0.02193902 -0.3291939 ]
[ 0.04797211  0.40910546 -0.0285229  -0.62871385]
[ 0.05615422  0.21439293 -0.04109718 -0.34514846]
[ 0.06044207  0.01987896 -0.04800015 -0.06570303]
[ 0.06083965 -0.17452311 -0.04931421  0.21145758]
[ 0.05734919  0.02126797 -0.04508506 -0.0963645 ]
[ 0.05777455  0.21700613 -0.04701235 -0.40292391]
[ 0.06211467  0.02258139 -0.05507082 -0.12542556]
[ 0.0625663  -0.17171013 -0.05757933  0.14938727]
[ 0.0591321  -0.36596232 -0.05459159  0.42336369]
[ 0.05181285 -0.56027011 -0.04612432  0.69834922]
[ 0.04060745 -0.36453999 -0.03215733  0.39151055]
[ 0.03331665 -0.55919116 -0.02432712  0.67388373]
[ 0.02213283 -0.75396671 -0.01084945  0.95880913]
[ 0.00705349 -0.94894113  0.00832674  1.24806387]
[-0.01192533 -1.14416885  0.03328801  1.54334333]
[-0.03480871 -1.33967466  0.06415488  1.84622445]
[-0.0616022  -1.53544209  0.10107937  2.15812009]
[-0.09231104 -1.73139931  0.14424177  2.48022237]
[-0.12693903 -1.92740233  0.19384622  2.81343391]


[-0.01029116  0.0417516   0.0849022   0.13492808]
[-0.00945613  0.23556131  0.08760077 -0.12980804]
[-0.0047449   0.03930081  0.08500461  0.18917557]
[-0.00395889 -0.15692791  0.08878812  0.50741712]
[-0.00709745  0.03683817  0.09893646  0.24398231]
[-0.00636068 -0.1595475   0.10381611  0.56616015]
[-0.00955163 -0.3559609   0.11513931  0.88966115]
[-0.01667085 -0.16257371  0.13293253  0.63527726]
[-0.01992233 -0.3592747   0.14563808  0.96669281]
[-0.02710782 -0.55602041  0.16497193  1.30135348]
[-0.03822823 -0.75280593  0.190999    1.64080617]
Episode finished after 17 timesteps
[ 0.0023049  -0.0293956   0.02101001  0.02690352]
[ 0.00171698  0.16541885  0.02154809 -0.25907717]
[ 0.00502536  0.36022666  0.01636654 -0.5448864 ]
[ 0.0122299   0.55511486  0.00546881 -0.83236799]
[ 0.02333219  0.3599186  -0.01117855 -0.53797016]
[ 0.03053056  0.16495558 -0.02193795 -0.24883032]
[ 0.03382968 -0.02984632 -0.02691456  0.03685297]
[ 0.03323275 -0.22457218 -0.0261775   0.32092405]
[ 0.02874131 -

In [8]:
print(env.action_space)

Discrete(2)


# ddpg

In [1]:
#https://towardsdatascience.com/deep-deterministic-policy-gradients-explained-2d94655a9b7b
# utils.py
import numpy as np
import gym
from collections import deque
import random

# Ornstein-Ulhenbeck Process
# Taken from #https://github.com/vitchyr/rlkit/blob/master/rlkit/exploration_strategies/ou_strategy.py
class OUNoise(object):
    def __init__(self, action_space, mu=0.0, theta=0.15, max_sigma=0.3, min_sigma=0.3, decay_period=100000):
        self.mu           = mu
        self.theta        = theta
        self.sigma        = max_sigma
        self.max_sigma    = max_sigma
        self.min_sigma    = min_sigma
        self.decay_period = decay_period
        self.action_dim   = action_space.shape[0]
        self.low          = action_space.low
        self.high         = action_space.high
        self.reset()
        
    def reset(self):
        self.state = np.ones(self.action_dim) * self.mu
        
    def evolve_state(self):
        x  = self.state
        dx = self.theta * (self.mu - x) + self.sigma * np.random.randn(self.action_dim)
        self.state = x + dx
        return self.state
    
    def get_action(self, action, t=0):
        ou_state = self.evolve_state()
        self.sigma = self.max_sigma - (self.max_sigma - self.min_sigma) * min(1.0, t / self.decay_period)
        return np.clip(action + ou_state, self.low, self.high)


# https://github.com/openai/gym/blob/master/gym/core.py
class NormalizedEnv(gym.ActionWrapper):
    """ Wrap action """

    def action(self, action):
        act_k = (self.action_space.high - self.action_space.low)/ 2.
        act_b = (self.action_space.high + self.action_space.low)/ 2.
        return act_k * action + act_b

    def reverse_action(self, action):
        act_k_inv = 2./(self.action_space.high - self.action_space.low)
        act_b = (self.action_space.high + self.action_space.low)/ 2.
        return act_k_inv * (action - act_b)
        

class Memory:
    def __init__(self, max_size):
        self.max_size = max_size
        self.buffer = deque(maxlen=max_size)
    
    def push(self, state, action, reward, next_state, done):
        experience = (state, action, np.array([reward]), next_state, done)
        self.buffer.append(experience)

    def sample(self, batch_size):
        state_batch = []
        action_batch = []
        reward_batch = []
        next_state_batch = []
        done_batch = []

        batch = random.sample(self.buffer, batch_size)

        for experience in batch:
            state, action, reward, next_state, done = experience
            state_batch.append(state)
            action_batch.append(action)
            reward_batch.append(reward)
            next_state_batch.append(next_state)
            done_batch.append(done)
        
        return state_batch, action_batch, reward_batch, next_state_batch, done_batch

    def __len__(self):
        return len(self.buffer)
    
class Memory:
    def __init__(self, max_size,state_size,action_size):
        self.max_size = max_size
        self.state_buf = np.zeros((max_size,state_size))
        self.action_buf = np.zeros((max_size,action_size))
        self.reward_buf = np.zeros((max_size,1))
        self.next_state_buf = np.zeros((max_size,state_size))
        self.done_buf = np.zeros(max_size,dtype=bool)
        self.index = 0
    
    def push(self, state, action, reward, next_state, done):
        k = self.index%self.max_size
        self.state_buf[k] = state
        self.action_buf[k] = action
        self.reward_buf[k] = reward
        self.next_state_buf[k] = next_state
        self.done_buf[k] = done
        self.index+=1

    def sample(self, batch_size):
        ids = np.random.choice(len(self),batch_size)
        state_batch = self.state_buf[ids]
        action_batch = self.action_buf[ids]
        reward_batch = self.reward_buf[ids]
        next_state_batch = self.next_state_buf[ids]
        done_batch = self.done_buf[ids]
        return state_batch, action_batch, reward_batch, next_state_batch, done_batch

    def __len__(self):
        return self.index if self.index<self.max_size else self.max_size

In [2]:
# models.py
import torch
import torch.nn as nn
import torch.nn.functional as F 
import torch.autograd
from torch.autograd import Variable

class Critic(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Critic, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.linear2 = nn.Linear(hidden_size, hidden_size)
        self.linear3 = nn.Linear(hidden_size, output_size)

    def forward(self, state, action):
        """
        Params state and actions are torch tensors
        """
        x = torch.cat([state, action], 1)
        x = F.relu(self.linear1(x))
        x = F.relu(self.linear2(x))
        x = self.linear3(x)

        return x

class Actor(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, learning_rate = 3e-4):
        super(Actor, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.linear2 = nn.Linear(hidden_size, hidden_size)
        self.linear3 = nn.Linear(hidden_size, output_size)
        
    def forward(self, state):
        """
        Param state is a torch tensor
        """
        x = F.relu(self.linear1(state))
        x = F.relu(self.linear2(x))
        x = torch.tanh(self.linear3(x))

        return x

In [3]:
# ddpg.py
import torch
import torch.autograd
import torch.optim as optim
import torch.nn as nn
# from model import *
# from utils import *

class DDPGagent:
    def __init__(self, env, hidden_size=512, 
                 actor_learning_rate=1e-4, critic_learning_rate=1e-3, 
                 gamma=0.99, tau=1e-2, max_memory_size=50000,device="cuda"):
        # Params
        self.num_states = env.observation_space.shape[0]
        self.num_actions = env.action_space.shape[0]
        self.gamma = gamma
        self.tau = tau
        self.device = device

        # Networks
        self.actor = Actor(self.num_states, hidden_size, self.num_actions).to(device)
        self.actor_target = Actor(self.num_states, hidden_size, self.num_actions).to(device)
        self.critic = Critic(self.num_states + self.num_actions, hidden_size, self.num_actions).to(device)
        self.critic_target = Critic(self.num_states + self.num_actions, hidden_size, self.num_actions).to(device)

        for target_param, param in zip(self.actor_target.parameters(), self.actor.parameters()):
            target_param.data.copy_(param.data)

        for target_param, param in zip(self.critic_target.parameters(), self.critic.parameters()):
            target_param.data.copy_(param.data)
        
        # Training
        self.memory = Memory(max_memory_size,self.num_states, self.num_actions)    
#         self.memory = Memory(max_memory_size)
        self.critic_criterion  = nn.MSELoss()
        self.actor_optimizer  = optim.Adam(self.actor.parameters(), lr=actor_learning_rate)
        self.critic_optimizer = optim.Adam(self.critic.parameters(), lr=critic_learning_rate)
    
    def get_action(self, state):
        state = Variable(torch.from_numpy(state).float().unsqueeze(0)).to(self.device)
        action = self.actor.forward(state)
        action = action.detach().cpu().numpy()[0,0]
        return action
    
    def update(self, batch_size):
        states, actions, rewards, next_states, _ = self.memory.sample(batch_size)
        states = torch.FloatTensor(states).to(self.device)
        actions = torch.FloatTensor(actions).to(self.device)
        rewards = torch.FloatTensor(rewards).to(self.device)
        next_states = torch.FloatTensor(next_states).to(self.device)
    
        # Critic loss        
        Qvals = self.critic.forward(states, actions)
        next_actions = self.actor_target.forward(next_states)
        next_Q = self.critic_target.forward(next_states, next_actions.detach())
        Qprime = rewards + self.gamma * next_Q
        critic_loss = self.critic_criterion(Qvals, Qprime)

        # Actor loss
        policy_loss = -self.critic.forward(states, self.actor.forward(states)).mean()
        
        # update networks
        self.actor_optimizer.zero_grad()
        policy_loss.backward()
        self.actor_optimizer.step()

        self.critic_optimizer.zero_grad()
        critic_loss.backward() 
        self.critic_optimizer.step()

        # update target networks 
        for target_param, param in zip(self.actor_target.parameters(), self.actor.parameters()):
            target_param.data.copy_(param.data * self.tau + target_param.data * (1.0 - self.tau))
       
        for target_param, param in zip(self.critic_target.parameters(), self.critic.parameters()):
            target_param.data.copy_(param.data * self.tau + target_param.data * (1.0 - self.tau))


In [14]:
# env = gym.make("Pendulum-v0")
# env.reset()
# env.step([0.1])

(array([ 0.98062095, -0.19591467, -0.87179786]),
 -0.08320917045968758,
 False,
 {})

In [4]:
import sys
import gym
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# from DDPG import DDPGagent
# from utils import *

# env = NormalizedEnv(gym.make("Pendulum-v0"))

env = gym.make("Pendulum-v0")


agent = DDPGagent(env)
noise = OUNoise(env.action_space)
batch_size = 256
rewards = []
avg_rewards = []

for episode in range(50):
    state = env.reset()
    noise.reset()
    episode_reward = 0
    
    for step in range(500):
        action = agent.get_action(state)
        action = noise.get_action(action, step)
        new_state, reward, done, _ = env.step(action) 
        agent.memory.push(state, action, reward, new_state, done)
        
        if len(agent.memory) > batch_size:
            agent.update(batch_size)        
        
        state = new_state
        episode_reward += reward
        if done:
            break

    rewards.append(episode_reward)
    avg_rewards.append(np.mean(rewards[-10:]))
    sys.stdout.write("episode: {}, reward: {}, average _reward: {} \n".format(episode, np.round(episode_reward, decimals=2), np.mean(rewards[-10:])))


plt.plot(rewards)
plt.plot(avg_rewards)
plt.plot()
plt.xlabel('Episode')
plt.ylabel('Reward')
plt.show()

KeyboardInterrupt: 

In [35]:
state = env.reset()
noise.reset()
episode_reward = 0

for step in range(500):
    env.render()
    action = agent.get_action(state)
    action = noise.get_action(action, step)
    new_state, reward, done, _ = env.step(action) 
    agent.memory.push(state, action, reward, new_state, done)

    if len(agent.memory) > batch_size:
        agent.update(batch_size)        

    state = new_state
    episode_reward += reward
    if done:
        break
env.close()


In [18]:
import gym
import subprocess
import time
import numpy as np
from collections import defaultdict
import msgpack
import socket

class FlexipodEnv(gym.Env):
    
    # name of command message
    CMD_NAME = ("header", "t", "cmd")

    # name of the returned message
    REC_NAME = ("header",
                "t",           # simulation time [s]
                "joint_pos",   # joint angle [rad]
                "joint_vel",   # joint velocity [rad/s]
                "actuation",   # joint actuation [-1,1]
                "orientation", # base link (body) orientation
                "ang_vel",     # base link (body) angular velocity [rad/s]
                "com_acc",     # base link (body) acceleration
                "com_vel",     # base link (body) velocity
                "com_pos"      # base link (body) position
                )

    ID =defaultdict(None,{name: k  for k,name in enumerate(REC_NAME)})
    CMD_ID = defaultdict(None,{name: k  for k,name in enumerate(CMD_NAME)})
    COMBINED_NAME = tuple(list(REC_NAME)[1:]+["cmd"])
    
    UDP_TERMINATE = -1
    UDP_PAUSE = 17
    UDP_RESUME = 16
    UDP_RESET = 15
    UDP_ROBOT_STATE_REPORT = 14
    UDP_MOTOR_VEL_COMMEND = 13
    UDP_STEP_MOTOR_VEL_COMMEND = 12
    UDP_MOTOR_POS_COMMEND = 11
    UDP_STEP_MOTOR_POS_COMMEND = 10
    
    def __init__(self, dof = 12,
           ip_local = "127.0.0.1", port_local = 32000,
           ip_remote = "127.0.0.1",port_remote = 32001):
        
        super(FlexipodEnv,self).__init__()
        self.local_address = (ip_local, port_local)
        self.remote_address = (ip_remote, port_remote)
        self.packer = msgpack.Packer(use_single_float=True, use_bin_type=True)
        
        self.dof = dof # num joints
        
        # joint_pos,joint_vel,actuation,orientation,ang_vel,com_acc,com_vel,com_pos.z
        state_size = self.dof * 3 + 6 + 3*3+1
        # state = np.empty(state_size,dtype=np.float32)
        action_size = self.dof
        self.max_action = 1.
        self.action_space = gym.spaces.Box(
            low= -self.max_action*np.ones(action_size,dtype=np.float32),
            high = self.max_action*np.ones(action_size,dtype=np.float32),
            dtype=np.float32)
        
        self.max_observation = np.hstack([
            np.ones(dof)*np.pi,  # joint_pos,
            np.ones(dof)*10.,   # joint_vel
            np.ones(dof),       # actuation
            np.ones(6),         # orientation
            np.ones(3)*30,      # ang_vel
            np.ones(3)*30,      # com_acc
            np.ones(3)*2,       # com_vel
            np.ones(1),         # com_pos_z
        ]).astype(np.float32)
        self.observation_space = gym.spaces.Box(
            low =-self.max_observation,
            high=self.max_observation,
#             shape = state_size,
            dtype = np.float32)

        # reset data packed # https://msgpack-python.readthedocs.io/en/latest/api.html#msgpack.Packer
        self.reset_cmd_b = self.packer.pack([self.UDP_RESET,0,[0,0,0,0]])
        self.pause_cmd_b = self.packer.pack([self.UDP_PAUSE,0,[0,0,0,0]])
        self.resume_cmd_b = self.packer.pack([self.UDP_RESUME,0,[0,0,0,0]])
        
        self.BUFFER_LEN = 512  # in bytes
        self.TIMEOUT = 0.5 #timeout duration
        
        self._startSocket()
#         gc.collect()

        
    def __del__(self): # Deleting (Calling destructor) 
        print('Destructor called, FlexipodEnv deleted.')
        self.close()
        
        
    def send(cmd):
        sock = socket.socket(socket.AF_INET,socket.SOCK_DGRAM) # UDP
        #Enable/disable immediate reuse of IP address
        sock.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
        #Set a timeout so the socket does not block indefinitely when trying to receive data
        self.sock.settimeout(self.TIMEOUT)
#         self.sock.setblocking(0)
        self.sock.bind(self.local_address) #Bind the socket to the port
    
    
    def step(self,action:list):
#         step_cmd_b = self.packer.pack([self.UDP_STEP_MOTOR_VEL_COMMEND,time.time(),action])
        step_cmd_b = self.packer.pack([self.UDP_MOTOR_VEL_COMMEND,time.time(),action if type(action) is list else action.tolist()])
        num_bytes_send = self.sock.sendto(step_cmd_b,self.remote_address)
        self._closeSocket()
        self._startSocket()
        data = self.sock.recv(self.BUFFER_LEN)
        msg_rec = msgpack.unpackb(data)
        return self._processRecMsg(msg_rec)

    def _processRecMsg(self,msg_rec):
        """processed received message to state action pair"""
        # joint_pos,joint_vel,actuation,orientation,ang_vel,com_acc,com_vel,com_pos.z
        observation = np.hstack(msg_rec[2:-1]+[msg_rec[-1][-1]]).astype(np.float32)
        reward = msg_rec[self.ID['orientation']][2]+msg_rec[self.ID['com_pos']][2]
        done = True if reward<0.8 else False
        return observation,reward,done, None
    
    def reset(self):
        time.sleep(1e-8)
        self._closeSocket()
        self._startSocket()
        num_bytes_send = self.sock.sendto(self.reset_cmd_b,self.remote_address)
        time.sleep(1e-8)
        num_bytes_send = self.sock.sendto(self.pause_cmd_b,self.remote_address)
        self._closeSocket()
        self._startSocket()
        data = self.sock.recv(self.BUFFER_LEN)
        msg_rec = msgpack.unpackb(data)
        return self._processRecMsg(msg_rec)[0]
    
    def render(self,mode="human"):
        pass
    def close(self):
        self._closeSocket()
            

    def _startSocket(self):
        # socket
        self.sock = socket.socket(socket.AF_INET,socket.SOCK_DGRAM) # UDP
        #Enable/disable immediate reuse of IP address
        self.sock.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
        #Set a timeout so the socket does not block indefinitely when trying to receive data
        self.sock.settimeout(self.TIMEOUT)
#         self.sock.setblocking(0)
        self.sock.bind(self.local_address) #Bind the socket to the port
        # self.sock.connect(remote_address)
        
    def _closeSocket(self):
        if self.sock and self.sock._closed:
            # for closing connection:
            self.sock.shutdown(socket.SHUT_RDWR)
            self.sock.close()
        
    def checkSimulation(self):
        try: # check if the simulation is opened
            data = self.sock.recv(self.BUFFER_LEN)
        except socket.timeout: # program not opened
#             task = subprocess.Popen(["../../build/flexipod.exe"])
#             time.sleep(self.TIMEOUT)
            raise OSError("felxipod program not opened")

    def receive(self):
#         if self.sock._closed:
#             self.sock.
        try:
            data = self.sock.recv(self.BUFFER_LEN)
            data_unpacked = msgpack.unpackb(data)
#             str_data = "".join([FlexipodEnv.item_to_String(n,d) for n,d in zip(self.REC_NAME,data_unpacked)])
#             print(str_data)
            return data_unpacked
        except Exception as e:
            print(e)
            pass
        
    def item_to_String(key,value):
        try:
            return f"{key:<12s}:{','.join(f'{k:>+6.2f}' for k in value)}\n"
        except:
            return f"{key:<12s}:{value:>+6.2f}\n"

In [19]:
env = FlexipodEnv(dof = 12)
# env.sock.sendto(env.resume_cmd_b,env.remote_address)
# env.sock.sendto(env.pause_cmd_b,env.remote_address)
# env.step((np.random.random(12)*1).tolist())
# for k in range(100):
#     env.reset()

Destructor called, FlexipodEnv deleted.


In [20]:
for k in range(3):
    env.reset()
    env.sock.sendto(env.resume_cmd_b,env.remote_address)
    for t in range(1000):
        observation,reward,done,_=env.step(((-0.5+np.random.random(12))*5).tolist())
        if done:
            break
#     env.sock.sendto(env.pause_cmd_b,env.remote_address)
env.sock.sendto(env.pause_cmd_b,env.remote_address)

8

In [21]:
import sys
import gym
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# from DDPG import DDPGagent
# from utils import *


env = NormalizedEnv(env)

agent = DDPGagent(env)
noise = OUNoise(env.action_space)
batch_size = 256
rewards = []
avg_rewards = []

In [22]:
for episode in range(3000):
    state = env.reset()
    noise.reset()
    episode_reward = 0
    env.sock.sendto(env.resume_cmd_b,env.remote_address)
    for step in range(2000):
        action = agent.get_action(state)
        action = noise.get_action(action, step)
        new_state, reward, done, _ = env.step(action) 
        agent.memory.push(state, action, reward, new_state, done)
        
        if len(agent.memory) > batch_size:
            agent.update(batch_size)        
        
        state = new_state
        episode_reward += reward
        if done:
            break

    rewards.append(episode_reward)
    avg_rewards.append(np.mean(rewards[-10:]))
    sys.stdout.write("episode: {}, reward: {}, average _reward: {} \n".format(episode, np.round(episode_reward, decimals=2), np.mean(rewards[-10:])))


plt.plot(rewards)
plt.plot(avg_rewards)
plt.plot()
plt.xlabel('Episode')
plt.ylabel('Reward')
plt.show()

episode: 0, reward: 202.67, average _reward: 202.67361030320598 
episode: 1, reward: 167.74, average _reward: 185.2091343478519 
episode: 2, reward: 83.66, average _reward: 151.36038721882144 
episode: 3, reward: 57.83, average _reward: 127.97661216811673 
episode: 4, reward: 74.04, average _reward: 117.19014074435844 
episode: 5, reward: 54.13, average _reward: 106.68005508583553 
episode: 6, reward: 60.19, average _reward: 100.0392780378291 
episode: 7, reward: 69.92, average _reward: 96.27397284966068 
episode: 8, reward: 66.36, average _reward: 92.95074549190774 
episode: 9, reward: 66.75, average _reward: 90.33071142265577 
episode: 10, reward: 73.47, average _reward: 77.41056722146722 
episode: 11, reward: 65.94, average _reward: 67.23022027194516 
episode: 12, reward: 71.76, average _reward: 66.03975139701011 
episode: 13, reward: 116.91, average _reward: 71.94785869095554 
episode: 14, reward: 105.07, average _reward: 75.05051466188416 
episode: 15, reward: 155.45, average _rew

episode: 128, reward: 69.93, average _reward: 86.05693280513294 
episode: 129, reward: 74.32, average _reward: 83.97045893051094 
episode: 130, reward: 55.71, average _reward: 81.76392891246809 
episode: 131, reward: 65.0, average _reward: 80.05775519206054 
episode: 132, reward: 92.22, average _reward: 78.55889979522371 
episode: 133, reward: 75.92, average _reward: 76.09830444428849 
episode: 134, reward: 75.15, average _reward: 76.00420678950636 
episode: 135, reward: 83.09, average _reward: 75.22760236656084 
episode: 136, reward: 66.77, average _reward: 71.93264353955996 
episode: 137, reward: 81.38, average _reward: 73.94904828318901 
episode: 138, reward: 80.54, average _reward: 75.01004647164322 
episode: 139, reward: 59.76, average _reward: 73.55366533494643 
episode: 140, reward: 64.4, average _reward: 74.42261475328628 
episode: 141, reward: 57.3, average _reward: 73.65244521024036 
episode: 142, reward: 89.64, average _reward: 73.39400990391876 
episode: 143, reward: 57.5, 

episode: 255, reward: 79.54, average _reward: 79.8495046546723 
episode: 256, reward: 74.45, average _reward: 80.26828453036003 
episode: 257, reward: 73.06, average _reward: 79.75608985366003 
episode: 258, reward: 57.27, average _reward: 78.78939943068528 
episode: 259, reward: 61.92, average _reward: 77.43598227121294 
episode: 260, reward: 61.65, average _reward: 76.65728793889797 
episode: 261, reward: 59.9, average _reward: 75.5878479779291 
episode: 262, reward: 61.38, average _reward: 70.78108583790905 
episode: 263, reward: 58.5, average _reward: 68.30974458872237 
episode: 264, reward: 56.03, average _reward: 64.37131556658147 
episode: 265, reward: 56.46, average _reward: 62.06308040021221 
episode: 266, reward: 67.83, average _reward: 61.401709598721425 
episode: 267, reward: 66.95, average _reward: 60.79081785420908 
episode: 268, reward: 53.21, average _reward: 60.384347560880954 
episode: 269, reward: 54.75, average _reward: 59.66703467961165 
episode: 270, reward: 57.48

episode: 381, reward: 10.45, average _reward: 12.334979717183653 
episode: 382, reward: 12.33, average _reward: 12.27306536584925 
episode: 383, reward: 11.99, average _reward: 12.226400849966828 
episode: 384, reward: 11.92, average _reward: 12.25169482194747 
episode: 385, reward: 10.7, average _reward: 12.03887641058879 
episode: 386, reward: 11.18, average _reward: 11.95454478888136 
episode: 387, reward: 10.95, average _reward: 11.98159683843593 
episode: 388, reward: 10.62, average _reward: 11.663785382244466 
episode: 389, reward: 14.14, average _reward: 11.978982327127607 
episode: 390, reward: 13.94, average _reward: 11.822302655069466 
episode: 391, reward: 12.58, average _reward: 12.03532599971101 
episode: 392, reward: 11.59, average _reward: 11.961514821341058 
episode: 393, reward: 9.31, average _reward: 11.692945735357366 
episode: 394, reward: 11.23, average _reward: 11.623868017555125 
episode: 395, reward: 9.27, average _reward: 11.481194799056677 
episode: 396, rewar

episode: 507, reward: 10.79, average _reward: 11.940785435766083 
episode: 508, reward: 10.57, average _reward: 11.887999223249086 
episode: 509, reward: 13.01, average _reward: 12.104847483078212 
episode: 510, reward: 12.38, average _reward: 12.075128813631416 
episode: 511, reward: 11.21, average _reward: 12.115601918653226 
episode: 512, reward: 13.55, average _reward: 12.21047819753895 
episode: 513, reward: 11.7, average _reward: 12.009593044399201 
episode: 514, reward: 11.07, average _reward: 12.017221742629072 
episode: 515, reward: 12.03, average _reward: 12.009970744044882 
episode: 516, reward: 11.13, average _reward: 11.745276587523541 
episode: 517, reward: 11.21, average _reward: 11.78716546813358 
episode: 518, reward: 13.21, average _reward: 12.050927031042919 
episode: 519, reward: 15.19, average _reward: 12.269585346059932 
episode: 520, reward: 12.76, average _reward: 12.307968359538574 
episode: 521, reward: 12.23, average _reward: 12.409707262179035 
episode: 522,

episode: 632, reward: 11.51, average _reward: 11.799925193858577 
episode: 633, reward: 12.6, average _reward: 11.734174238564163 
episode: 634, reward: 12.05, average _reward: 11.775100656838607 
episode: 635, reward: 12.6, average _reward: 11.919148638684394 
episode: 636, reward: 11.35, average _reward: 11.829124029315 
episode: 637, reward: 9.9, average _reward: 11.632977546212036 
episode: 638, reward: 13.62, average _reward: 11.87639306194089 
episode: 639, reward: 14.62, average _reward: 12.110493907754543 
episode: 640, reward: 13.17, average _reward: 12.261174934312399 
episode: 641, reward: 13.32, average _reward: 12.474222242417845 
episode: 642, reward: 12.26, average _reward: 12.549272794978 
episode: 643, reward: 12.14, average _reward: 12.503441597486152 
episode: 644, reward: 12.55, average _reward: 12.554150007777372 
episode: 645, reward: 12.1, average _reward: 12.504717062050767 
episode: 646, reward: 11.92, average _reward: 12.561895198123972 
episode: 647, reward: 

episode: 757, reward: 11.01, average _reward: 11.860832715328005 
episode: 758, reward: 21.62, average _reward: 12.703730949552273 
episode: 759, reward: 13.0, average _reward: 12.781918789403559 
episode: 760, reward: 12.04, average _reward: 12.730076708928019 
episode: 761, reward: 14.56, average _reward: 12.935397124696683 
episode: 762, reward: 12.24, average _reward: 13.094791242718552 
episode: 763, reward: 11.98, average _reward: 13.14255816159367 
episode: 764, reward: 12.42, average _reward: 13.171453146465273 
episode: 765, reward: 12.84, average _reward: 13.248724107595782 
episode: 766, reward: 9.33, average _reward: 13.105540481795236 
episode: 767, reward: 12.24, average _reward: 13.22822455564192 
episode: 768, reward: 12.4, average _reward: 12.306081891215355 
episode: 769, reward: 17.67, average _reward: 12.77215208288288 
episode: 770, reward: 11.12, average _reward: 12.679993935008055 
episode: 771, reward: 14.24, average _reward: 12.647392995735762 
episode: 772, re

KeyboardInterrupt: 

In [16]:
for episode in range(1):
    state = env.reset()
    noise.reset()
    episode_reward = 0
    env.sock.sendto(env.resume_cmd_b,env.remote_address)
    for step in range(2000):
        action = agent.get_action(state)
        new_state, reward, done, _ = env.step(action)   
        
        state = new_state
        episode_reward += reward
        if done:
            break
